workflow:
  name: "Titanic ML Retraining CI"
  version: "2.0"
  author: "Mohamad Rizki"

ci:
  trigger:
    - push to main branch
  mlflow_project_path: "./MLProject"
  docker_image: "mok111/titanic-mlflow:latest"
  
  retraining:
    command: "mlflow run ."