name: CI - MLflow Project Retraining

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  mlflow-retraining:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          pip install pandas numpy scikit-learn mlflow
      
      - name: Run training script
        run: |
          cd MLProject
          python modelling.py
      
      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: MLProject/best_model.pkl